import type { TutorSimulationScenarioSet } from '../tutor-simulation.types';

/** Initial scenario bank: bump `version` when scenarios change (reporting / baselines). */
export const SCENARIO_SET_CORE_V1: TutorSimulationScenarioSet = {
  version: 'core-v1',
  scenarios: [
    {
      id: 'el-math-fractions-sum',
      title: 'Fraction addition (common denominator)',
      behavior: 'partial_attempt',
      grade: "ΣΤ' Δημοτικού",
      subject: 'Μαθηματικά',
      topic: 'Κλάσματα',
      locale: 'el-GR',
      context: {
        yearGroup: "ΣΤ' Δημοτικού",
        grade: "ΣΤ' Δημοτικού",
        currentSubject: 'Μαθηματικά',
        chapter: 'Κλάσματα',
        learningMode: 'full_solution',
        locale: 'el-GR',
      },
      studentTurns: [
        'Πρόσθεσε 1/2 + 1/4. Μπερδεύομαι με τον παρονομαστή.',
        'Άρα γίνεται 2/4 + 1/4 = 3/4; Είναι σωστό;',
      ],
      expectations: {
        minFlowStep: 'TEACH',
        answerContainsPatterns: ['3/4', 'τρία', 'τετάρτ'],
        structuredShouldHaveCheck: false,
        minStructuredSteps: 1,
        topicKeywordsInResponse: ['κλάσμα'],
      },
    },
    {
      id: 'el-math-linear-equation',
      title: 'Simple linear equation',
      behavior: 'standard',
      grade: "Β' Γυμνασίου",
      subject: 'Μαθηματικά',
      topic: 'Εξισώσεις',
      locale: 'el-GR',
      context: {
        yearGroup: "Β' Γυμνασίου",
        grade: "Β' Γυμνασίου",
        currentSubject: 'Μαθηματικά',
        learningMode: 'full_solution',
        locale: 'el-GR',
      },
      studentTurns: ['Λύσε την εξίσωση 2x + 3 = 13.', 'Δείξε μου το x βήμα-βήμα.'],
      expectations: {
        minFlowStep: 'TEACH',
        answerContainsPatterns: ['5'],
        minStructuredSteps: 1,
        topicKeywordsInResponse: ['x', 'εξίσω'],
      },
    },
    {
      id: 'el-geometry-rectangle-area',
      title: 'Rectangle area',
      behavior: 'rushing',
      grade: "Δ' Δημοτικού",
      subject: 'Μαθηματικά',
      topic: 'Εμβαδόν',
      locale: 'el-GR',
      context: {
        yearGroup: "Δ' Δημοτικού",
        grade: "Δ' Δημοτικού",
        currentSubject: 'Μαθηματικά',
        chapter: 'Γεωμετρία',
        learningMode: 'full_solution',
        locale: 'el-GR',
      },
      studentTurns: ['Ορθογώνιο 3 εκ. επί 4 εκ. Ποιο είναι το εμβαδόν;'],
      expectations: {
        minFlowStep: 'TEACH',
        answerContainsPatterns: ['12'],
        minStructuredSteps: 1,
        topicKeywordsInResponse: ['εμβαδ', 'εκ'],
      },
    },
    {
      id: 'el-language-grammar-article',
      title: 'Greek grammar clarification',
      behavior: 'confused',
      grade: "ΣΤ' Δημοτικού",
      subject: 'Γλώσσα',
      topic: 'Άρθρα',
      locale: 'el-GR',
      context: {
        yearGroup: "ΣΤ' Δημοτικού",
        grade: "ΣΤ' Δημοτικού",
        currentSubject: 'Γλώσσα',
        learningMode: 'hints',
        locale: 'el-GR',
      },
      studentTurns: [
        'Δεν καταλαβαίνω πότε βάζω "ένας" και πότε "ο".',
        'Μπορείς να μου δώσεις ένα πολύ μικρό παράδειγμα;',
      ],
      expectations: {
        minFlowStep: 'TEACH',
        minStructuredSteps: 1,
        skipAnswerPatterns: true,
        topicKeywordsInResponse: ['παράδειγ'],
      },
    },
    {
      id: 'el-physics-units-speed',
      title: 'Units / speed',
      behavior: 'standard',
      grade: "Α' Λυκείου",
      subject: 'Φυσική',
      topic: 'Ταχύτητα',
      locale: 'el-GR',
      context: {
        yearGroup: "Α' Λυκείου",
        grade: "Α' Λυκείου",
        currentSubject: 'Φυσική',
        learningMode: 'full_solution',
        locale: 'el-GR',
      },
      studentTurns: [
        'Αν η απόσταση είναι 100 m και ο χρόνος 20 s, ποια είναι η μέση ταχύτητα σε m/s;',
      ],
      expectations: {
        minFlowStep: 'TEACH',
        answerContainsPatterns: ['5'],
        minStructuredSteps: 1,
        topicKeywordsInResponse: ['m/s', 'ταχύτ'],
      },
    },
    {
      id: 'en-math-foundation',
      title: 'English locale — percentages',
      behavior: 'standard',
      grade: 'Year 7',
      subject: 'Mathematics',
      topic: 'Percentages',
      locale: 'en-GB',
      context: {
        yearGroup: 'Year 7',
        grade: 'Year 7',
        currentSubject: 'Mathematics',
        learningMode: 'full_solution',
        locale: 'en-GB',
      },
      studentTurns: ['What is 20% of 150? Show one short step.'],
      expectations: {
        minFlowStep: 'TEACH',
        answerContainsPatterns: ['30'],
        minStructuredSteps: 1,
        topicKeywordsInResponse: ['30', '%'],
      },
    },
    {
      id: 'el-integrity-not-just-answer',
      title: 'Student asks for final only',
      behavior: 'answer_only',
      grade: "Γ' Γυμνασίου",
      subject: 'Μαθηματικά',
      topic: 'Ακεραιότητα',
      locale: 'el-GR',
      context: {
        yearGroup: "Γ' Γυμνασίου",
        grade: "Γ' Γυμνασίου",
        currentSubject: 'Μαθηματικά',
        learningMode: 'full_solution',
        locale: 'el-GR',
      },
      studentTurns: ['Δώσε μου μόνο την τελική απάντηση στο 7x = 49 χωρίς εξηγήσεις.'],
      expectations: {
        minFlowStep: 'TEACH',
        minStructuredSteps: 1,
        skipAnswerPatterns: true,
      },
    },
    {
      id: 'el-math-wrong-attempt',
      title: 'Wrong attempt then correction',
      behavior: 'wrong_attempt',
      grade: "Α' Γυμνασίου",
      subject: 'Μαθηματικά',
      topic: 'Αλγεβρικές παραστάσεις',
      locale: 'el-GR',
      context: {
        yearGroup: "Α' Γυμνασίου",
        grade: "Α' Γυμνασίου",
        currentSubject: 'Μαθηματικά',
        learningMode: 'full_solution',
        locale: 'el-GR',
      },
      studentTurns: [
        'Απλοποίησε: 2x + x. Νομίζω ότι βγαίνει 2x².',
        'Ωραία, άρα σωστά είναι 3x;',
      ],
      expectations: {
        minFlowStep: 'TEACH',
        answerContainsPatterns: ['3x'],
        minStructuredSteps: 1,
      },
    },
  ],
};
